apiVersion: batch/v1
kind: Job
metadata:
  namespace: kueue-jobs-ns-a # Job under team-a namespace
  generateName: job-lq-a-
  annotations:
    kueue.x-k8s.io/queue-name: local-queue-a # Point to the LocalQueue
spec:
  ttlSecondsAfterFinished: 60 # Job will be deleted after 60 seconds
  parallelism: 3 # This Job will have 3 replicas running at the same time
  completions: 3 # This Job requires 3 completions
  suspend: true # Set to true to allow Kueue to control the Job when it starts
  template:
    spec:
      containers:
        - name: dummy-job
          image: gcr.io/k8s-staging-perf-tests/sleep:latest
          args: ["60s"] # Sleep for 60 seconds
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
      restartPolicy: Never
